name: CI

on:
  pull_request:
    branches: [main, staging]
  push:
    branches: [main, staging]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/setup-frontend

      - name: Lint
        run: pnpm lint
        working-directory: applications/frontend

      - name: Build
        run: pnpm build
        working-directory: applications/frontend
        env:
          NEXT_PUBLIC_USE_FIREBASE_EMULATOR: "true"
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: demo-hut

      - name: Test
        run: pnpm test
        working-directory: applications/frontend
